
import React, { useMemo } from "react"
import { useAtomValue } from "jotai"
import { ExtensionStateContext, ExtensionStateContextType } from "../../../context/ExtensionStateContext"
import { ToolThemeProvider } from "../../../context/ToolThemeContext"
import { sessionMessagesAtomFamily } from "../state/atoms/messages"
import { DEFAULT_CHECKPOINT_TIMEOUT_SECONDS, ORGANIZATION_ALLOW_ALL } from "@roo-code/types"
import { defaultModeSlug, defaultPrompts } from "@roo/modes"
import { experimentDefault } from "@roo/experiments"

interface AgentManagerExtensionStateAdapterProps {
    children: React.ReactNode
    sessionId: string
}

/**
 * Adapts the Agent Manager Jotai state to the ExtensionStateContext expected by ChatRow.
 * This allows reusing the main ChatRow component within the Agent Manager.
 */
export const AgentManagerExtensionStateAdapter = ({ children, sessionId }: AgentManagerExtensionStateAdapterProps) => {
    const messages = useAtomValue(sessionMessagesAtomFamily(sessionId))
    const noop = () => {}

    const contextValue: ExtensionStateContextType = useMemo(() => {
        // Create a mock context with safe defaults for ChatRow
        return {
            // Session data
            clineMessages: messages,
            apiConfiguration: {}, // TODO: Pass from session if available
            currentTaskTodos: [], // TODO: Extract from messages if needed

            // Global defaults
            version: "0.0.0",
            didHydrateState: true,
            showWelcome: false,
            shouldShowAnnouncement: false,
            taskHistoryFullLength: 0,
            taskHistoryVersion: 0,
            cloudUserInfo: null,
            theme: undefined,
            mcpServers: [],
            mcpMarketplaceCatalog: { items: [] },
            currentCheckpoint: undefined,
            filePaths: [],
            openedTabs: [],
            globalRules: {},
            localRules: {},
            globalWorkflows: {},
            localWorkflows: {},
            commands: [],
            soundVolume: 0.5,
            ttsSpeed: 1.0,
            fuzzyMatchThreshold: 1.0,
            writeDelayMs: 1000,
            screenshotQuality: 75,
            routerModels: undefined,
            cloudIsAuthenticated: false,
            cloudOrganizations: [],
            organizationSettingsVersion: 1,
            marketplaceItems: [],
            marketplaceInstalledMetadata: { project: {}, global: {} },
            profileThresholds: {},
            alwaysAllowFollowupQuestions: false,
            followupAutoApproveTimeoutMs: undefined,
            interactionDelaySeconds: 0,
            remoteControlEnabled: false,
            taskSyncEnabled: false,
            featureRoomoteControlEnabled: false,

            // Setters (no-op for Agent Manager view mostly)
            setExperimentEnabled: noop,
            setApiConfiguration: noop,
            setCustomInstructions: noop,
            setAlwaysAllowReadOnly: noop,
            setAlwaysAllowReadOnlyOutsideWorkspace: noop,
            setAlwaysAllowWrite: noop,
            setAlwaysAllowWriteOutsideWorkspace: noop,
            setAlwaysAllowDelete: noop,
            setAlwaysAllowExecute: noop,
            setAlwaysAllowBrowser: noop,
            setAlwaysAllowMcp: noop,
            setAlwaysAllowModeSwitch: noop,
            setAlwaysAllowSubtasks: noop,
            setAlwaysAllowFollowupQuestions: noop,
            setFollowupAutoApproveTimeoutMs: noop,
            setShowAnnouncement: noop,
            setAllowedCommands: noop,
            setDeniedCommands: noop,
            setAllowedMaxRequests: noop,
            setAllowedMaxCost: noop,
            setSoundEnabled: noop,
            setSoundVolume: noop,
            setSlidingWindowSize: noop,
            setTtsEnabled: noop,
            setTtsSpeed: noop,
            setDiffEnabled: noop,
            setEnableCheckpoints: noop,
            setCheckpointTimeout: noop,
            setBrowserViewportSize: noop,
            setFuzzyMatchThreshold: noop,
            setWriteDelayMs: noop,
            setScreenshotQuality: noop,
            setTerminalOutputLineLimit: noop,
            setTerminalOutputCharacterLimit: noop,
            setTerminalShellIntegrationTimeout: noop,
            setTerminalShellIntegrationDisabled: noop,
            setTerminalZdotdir: noop,
            setMcpEnabled: noop,
            setEnableMcpServerCreation: noop,
            setRemoteControlEnabled: noop,
            setTaskSyncEnabled: noop,
            setFeatureRoomoteControlEnabled: noop,
            setAlwaysApproveResubmit: noop,
            setRequestDelaySeconds: noop,
            setCurrentApiConfigName: noop,
            setListApiConfigMeta: noop,
            setMode: noop,
            setCustomModePrompts: noop,
            setCustomSupportPrompts: noop,
            setEnhancementApiConfigId: noop,
            markNotificationAsDismissed: noop,
            setGhostServiceSettings: noop,
            setCommitMessageApiConfigId: noop,
            setShowAutoApproveMenu: noop,
            setShowTaskTimeline: noop,
            setSendMessageOnEnter: noop,
            setHideCostBelowThreshold: noop,
            setCollapseCodeToolsByDefault: noop,
            setHoveringTaskTimeline: noop,
            setShowTimestamps: noop,
			setAutoApprovalEnabled: noop,
            setCustomModes: noop,
            setMaxOpenTabsContext: noop,
            setMaxWorkspaceFiles: noop,
            setBrowserToolEnabled: noop,
            setDisableBrowserHeadless: noop, // kilocode_change
            setTelemetrySetting: noop,
            setShowRooIgnoredFiles: noop,
            setRemoteBrowserEnabled: noop,
            setAwsUsePromptCache: noop,
            setMaxReadFileLine: noop,
            setMaxImageFileSize: noop,
            setMaxTotalImageSize: noop,
            setPinnedApiConfigs: noop,
            setTerminalCompressProgressBar: noop,
            togglePinnedApiConfig: noop,
            setHistoryPreviewCollapsed: noop,
            setReasoningBlockCollapsed: noop,
            setEnterBehavior: noop,
            setHasOpenedModeSelector: noop,
            setAutoCondenseContext: noop,
            setAutoCondenseContextPercent: noop,
            setInfinityEnabled: noop,
            setInfinityPrompt: noop,
            setInfinityIntervalMinutes: noop,
            setInfinityIsRunning: noop,
            setInfinityScheduleType: noop,
            setInfinityScheduleHour: noop,
            setInfinityScheduleMinute: noop,
            setInfinityNextRunAt: noop,
            setInfinitySavedPrompts: noop,
            setActiveInfinityPromptId: noop,
            setCondensingApiConfigId: noop,
            setCustomCondensingPrompt: noop,
            setYoloGatekeeperApiConfigId: noop,
            setProfileThresholds: noop,
            setSubAgentToolEnabled: noop,
            setShowSubAgentBanner: noop,
            setSystemNotificationsEnabled: noop,
            setAlwaysAllowUpdateTodoList: noop,
            setIncludeDiagnosticMessages: noop,
            setMaxDiagnosticMessages: noop,
            setAutoPurgeEnabled: noop,
            setAutoPurgeDefaultRetentionDays: noop,
            setAutoPurgeFavoritedTaskRetentionDays: noop,
            setAutoPurgeCompletedTaskRetentionDays: noop,
            setAutoPurgeIncompleteTaskRetentionDays: noop,
            setAutoPurgeLastRunTimestamp: noop,
            setIncludeTaskHistoryInEnhance: noop,
            setIncludeCurrentTime: noop,
            setIncludeCurrentCost: noop,

            // Other state properties
            showTaskTimeline: true,
            sendMessageOnEnter: true,
            showTimestamps: true,
            hideCostBelowThreshold: -1,
            collapseCodeToolsByDefault: false,
            hoveringTaskTimeline: false,
            systemNotificationsEnabled: false,
            dismissedNotificationIds: [],
			autoPurgeEnabled: false,
            autoPurgeDefaultRetentionDays: 30,
            autoPurgeFavoritedTaskRetentionDays: null,
            autoPurgeCompletedTaskRetentionDays: 30,
            autoPurgeIncompleteTaskRetentionDays: 7,
            autoPurgeLastRunTimestamp: undefined,
            alwaysAllowUpdateTodoList: true,
            includeDiagnosticMessages: true,
            maxDiagnosticMessages: 50,
            reasoningBlockCollapsed: true,
            historyPreviewCollapsed: false,
            enterBehavior: "send",
            hasOpenedModeSelector: false,
            autoCondenseContext: true,
            autoCondenseContextPercent: 100,
            allowedCommands: [],
            deniedCommands: [],
            soundEnabled: false,
            isBrowserSessionActive: false,
            ttsEnabled: false,
            diffEnabled: false,
            enableCheckpoints: false,
            checkpointTimeout: DEFAULT_CHECKPOINT_TIMEOUT_SECONDS,
            language: "en",
            browserViewportSize: "900x600",
            terminalOutputLineLimit: 500,
            terminalOutputCharacterLimit: 50000,
            terminalShellIntegrationTimeout: 4000,
            mcpEnabled: true,
            enableMcpServerCreation: false,
            alwaysApproveResubmit: false,
            alwaysAllowWrite: true,
            alwaysAllowReadOnly: true,
            requestDelaySeconds: 5,
            currentApiConfigName: "default",
            listApiConfigMeta: [],
            mode: defaultModeSlug,
            customModePrompts: defaultPrompts,
            customSupportPrompts: {},
            experiments: experimentDefault,
            enhancementApiConfigId: "",
            commitMessageApiConfigId: "",
            ghostServiceSettings: {},
            condensingApiConfigId: "",
            customCondensingPrompt: "",
            yoloGatekeeperApiConfigId: "",
            autoApprovalEnabled: true,
            customModes: [],
            maxOpenTabsContext: 20,
            maxWorkspaceFiles: 200,
            cwd: "",
            browserToolEnabled: true,
            telemetrySetting: "unset",
            showRooIgnoredFiles: true,
            showAutoApproveMenu: false,
            renderContext: "sidebar",
            maxReadFileLine: -1,
            maxImageFileSize: 5,
            maxTotalImageSize: 20,
            pinnedApiConfigs: {},
            terminalZshOhMy: false,
            maxConcurrentFileReads: 5,
            allowVeryLargeReads: false,
            terminalZshP10k: false,
            terminalZdotdir: false,
            terminalCompressProgressBar: true,
            kilocodeDefaultModel: "anthropic/claude-3-5-sonnet-20240620",
            organizationAllowList: ORGANIZATION_ALLOW_ALL,
            sharingEnabled: false,
            codebaseIndexConfig: {
                codebaseIndexEnabled: true,
                codebaseIndexQdrantUrl: "http://localhost:6333",
                codebaseIndexEmbedderProvider: "openai",
                codebaseIndexVectorStoreProvider: "qdrant",
                codebaseIndexLancedbVectorStoreDirectory: undefined,
                codebaseIndexEmbedderBaseUrl: "",
                codebaseIndexEmbedderModelId: "",
                codebaseIndexSearchMaxResults: undefined,
                codebaseIndexSearchMinScore: undefined,
            },
            codebaseIndexModels: { ollama: {}, openai: {} },
            openRouterImageApiKey: "",
            kiloCodeImageApiKey: "",
            openRouterImageGenerationSelectedModel: "",
            includeCurrentTime: true,
            includeCurrentCost: true,
            includeTaskHistoryInEnhance: true,
            infinityEnabled: false,
            infinityPrompt: "",
            infinityIntervalMinutes: 5,
            infinityIsRunning: false,
            infinityScheduleType: "interval",
            infinityScheduleHour: 9,
            infinityScheduleMinute: 0,
            infinityNextRunAt: undefined,
            infinitySavedPrompts: [],
            activeInfinityPromptId: undefined,
            subAgentToolEnabled: false,
            showSubAgentBanner: true,
        } as ExtensionStateContextType
    }, [messages])

    return (
        <ToolThemeProvider>
            <ExtensionStateContext.Provider value={contextValue}>{children}</ExtensionStateContext.Provider>
        </ToolThemeProvider>
    )
}
