import {
	type ProviderName,
	type ModelInfo,
	anthropicModels,
	bedrockModels,
	cerebrasModels,
	claudeCodeModels,
	deepSeekModels,
	moonshotModels,
	// kade_change start
	// geminiModels,
	// geminiModels,
	geminiCliModels,
	cliProxyModels,
	// kade_change end
	mistralModels,
	openAiNativeModels,
	qwenCodeModels,
	vertexModels,
	xaiModels,
	groqModels,
	sambaNovaModels,
	doubaoModels,
	internationalZAiModels,
	fireworksModels,
	rooModels,
	featherlessModels,
	minimaxModels,
	basetenModels,
	antigravityModels,
	openAiCodexModels,
	kiroModels,
} from "@roo-code/types"

export const MODELS_BY_PROVIDER: Partial<Record<ProviderName, Record<string, ModelInfo>>> = {
	anthropic: anthropicModels,
	"claude-code": claudeCodeModels,
	bedrock: bedrockModels,
	cerebras: cerebrasModels,
	deepseek: deepSeekModels,
	doubao: doubaoModels,
	moonshot: moonshotModels,
	// kade_change start
	// gemini: geminiModels,
	"gemini-cli": geminiCliModels,
	"cli-proxy": cliProxyModels,
	// kade_change end
	mistral: mistralModels,
	"openai-native": openAiNativeModels,
	"qwen-code": qwenCodeModels,
	vertex: vertexModels,
	xai: xaiModels,
	groq: groqModels,
	// chutes: chutesModels, // kade_change
	sambanova: sambaNovaModels,
	zai: internationalZAiModels,
	fireworks: fireworksModels,
	roo: rooModels,
	featherless: featherlessModels,
	minimax: minimaxModels,
	baseten: basetenModels,
	"openai-codex": openAiCodexModels,
	antigravity: antigravityModels,
	kiro: kiroModels,
}

export const PROVIDERS = [
	{ value: "openrouter", label: "OpenRouter", website: "https://openrouter.ai" },
	{ value: "deepinfra", label: "DeepInfra", website: "https://deepinfra.com" },
	{ value: "anthropic", label: "Anthropic", website: "https://anthropic.com" },
	{ value: "claude-code", label: "Claude Code", website: "https://anthropic.com/claude" },
	{ value: "cerebras", label: "Cerebras", website: "https://cerebras.ai" },
	{ value: "gemini", label: "Google Gemini", website: "https://ai.google.dev" },
	{ value: "antigravity", label: "Google Gemini (Antigravity)", website: "https://cloud.google.com/vertex-ai/docs/generative-ai/code/code-assistance" },
	{ value: "doubao", label: "Doubao", website: "https://www.volcengine.com/product/ark" },

	// kade_change start
	{ value: "inception", label: "Inception", website: "https://inceptionlabs.ai" },
	{ value: "gemini-cli", label: "Google Gemini CLI (OAuth)", website: "https://ai.google.dev" },
	{ value: "virtual-quota-fallback", label: "Virtual Quota Fallback", website: "https://kilo.ai" },
	{ value: "synthetic", label: "Synthetic", website: "https://kilo.ai" },
	{ value: "ovhcloud", label: "OVHcloud AI Endpoints", website: "https://www.ovhcloud.com/en/lp/ai-endpoints" },
	{ value: "sap-ai-core", label: "SAP AI Core", website: "https://www.sap.com/products/technology-platform/ai-core.html" },
	{ value: "opencode", label: "OpenCode", website: "https://opencode.ai" },
	{ value: "cli-proxy", label: "Cli Proxy", website: "https://kilo.ai" },
	// kade_change end
	{ value: "deepseek", label: "DeepSeek", website: "https://deepseek.com" },
	{ value: "moonshot", label: "Moonshot", website: "https://moonshot.cn" },
	{ value: "openai-native", label: "OpenAI (Native)", website: "https://openai.com" },
	{ value: "openai-codex", label: "OpenAI Codex (OAuth)", website: "https://openai.com/codex" },
	{ value: "openai", label: "Custom OpenAI Compatible", website: "https://openai.com" },
	{ value: "qwen-code", label: "Qwen Code", website: "https://qwenlm.ai" },
	{ value: "vertex", label: "GCP Vertex AI", website: "https://cloud.google.com/vertex-ai" },
	{ value: "bedrock", label: "Amazon Bedrock", website: "https://aws.amazon.com/bedrock" },
	{ value: "glama", label: "Glama", website: "https://glama.ai" }, // kade_change
	{ value: "nano-gpt", label: "Nano-GPT", website: "https://nano-gpt.com" }, //kade_change
	{ value: "vscode-lm", label: "VS Code LM API", website: "https://code.visualstudio.com" },
	{ value: "mistral", label: "Mistral", website: "https://mistral.ai" },
	{ value: "lmstudio", label: "LM Studio", website: "https://lmstudio.ai" },
	{ value: "ollama", label: "Ollama", website: "https://ollama.com" },
	{ value: "unbound", label: "Unbound", website: "https://getunbound.ai" },
	{ value: "requesty", label: "Requesty", website: "https://requesty.ai" },
	{ value: "human-relay", label: "Human Relay", website: "https://kilo.ai" },
	{ value: "xai", label: "xAI (Grok)", website: "https://x.ai" },
	{ value: "groq", label: "Groq", website: "https://groq.com" },
	{ value: "huggingface", label: "Hugging Face", website: "https://huggingface.co" },
	{ value: "chutes", label: "Chutes AI", website: "https://chutes.ai" },
	{ value: "litellm", label: "LiteLLM", website: "https://litellm.ai" },
	{ value: "sambanova", label: "SambaNova", website: "https://sambanova.ai" },
	{ value: "zai", label: "Z.ai", website: "https://z.ai" },
	{ value: "fireworks", label: "Fireworks AI", website: "https://fireworks.ai" },
	{ value: "featherless", label: "Featherless AI", website: "https://featherless.ai" },
	{ value: "io-intelligence", label: "IO Intelligence", website: "https://io-intelligence.ai" },
	// kade_change start
	// { value: "roo", label: "Roo Code Cloud", website: "https://kilo.ai" },
	// kade_change end
	{ value: "vercel-ai-gateway", label: "Vercel AI Gateway", website: "https://vercel.com/ai" },
	{ value: "minimax", label: "MiniMax", website: "https://minimaxi.com" },
	{ value: "baseten", label: "Baseten", website: "https://baseten.co" },
	{ value: "kiro", label: "Kiro", website: "http://localhost:8000" },
	{ value: "kilocode", label: "Kilo Gateway", website: "https://kilo.ai" }, // kade_change
].sort((a, b) => a.label.localeCompare(b.label))
